# Generated by Django 4.2.16 on 2024-11-16 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название мероприятия"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата и время мероприятия")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание мероприятия"),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SubscribeUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Nikname")),
                (
                    "telegram_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "date_registered",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="events.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписчик",
                "verbose_name_plural": "Подписчики",
                "ordering": ["-date_registered"],
            },
        ),
    ]
