# Generated by Django 4.2.16 on 2024-12-02 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0002_alter_event_options_event_type_alter_event_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_slot", models.DateTimeField(verbose_name="Time Slot")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slot",
                "verbose_name_plural": "Slots",
                "ordering": ["time_slot"],
            },
        ),
        migrations.CreateModel(
            name="BookingSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Telegram ID",
                    ),
                ),
                (
                    "canceled_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Canceled Date"
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="bookings.slot",
                        verbose_name="Slot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Slot",
                "verbose_name_plural": "Booking Slots",
                "ordering": ["slot__time_slot"],
            },
        ),
    ]
